name: deliveryboy_multivendor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: 1.2.1
  shared_preferences: ^2.2.3
  connectivity_plus: 6.1.3
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  fluttertoast: ^8.2.5
  jaguar_jwt: ^3.0.0
  country_code_picker: ^3.0.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: 17.1.2
  path_provider: ^2.1.2
  sms_autofill: 2.3.1
  firebase_auth: ^4.17.8
  url_launcher: ^6.2.6
  intl: ^0.18.1
  flutter_svg: ^1.1.4
  firebase_core: ^2.27.0
  permission_handler: ^11.3.1
  cloud_firestore: ^4.0.1
  file_picker: ^8.0.0+1
  time_picker_sheet: ^0.0.2+1
  image_picker: ^0.8.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/opensans-regular.ttf
